// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: app.proto

package server

import (
	"context"

	"go-zero-box-rpc/app/internal/logic/user"
	"go-zero-box-rpc/app/internal/svc"
	"go-zero-box-rpc/app/rpc/user_rpc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user_rpc.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user_rpc.UserLoginReq) (*user_rpc.UserLoginResp, error) {
	l := userlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *user_rpc.UserRegisterReq) (*user_rpc.UserRegisterResp, error) {
	l := userlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Info(ctx context.Context, in *user_rpc.UserInfoReq) (*user_rpc.UserInfoResp, error) {
	l := userlogic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}
