// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: app.proto

package server

import (
	"context"

	user2 "github.com/prf16/go-zero-box-rpc/app/api/user"
	"github.com/prf16/go-zero-box-rpc/app/internal/logic/user"
	"github.com/prf16/go-zero-box-rpc/app/internal/svc"
)

type UserServer struct {
	svcCtx *svc.ServiceContext
	user2.UnimplementedUserServer
}

func NewUserServer(svcCtx *svc.ServiceContext) *UserServer {
	return &UserServer{
		svcCtx: svcCtx,
	}
}

func (s *UserServer) Login(ctx context.Context, in *user2.UserLoginReq) (*user2.UserLoginResp, error) {
	l := userlogic.NewLoginLogic(ctx, s.svcCtx)
	return l.Login(in)
}

func (s *UserServer) Register(ctx context.Context, in *user2.UserRegisterReq) (*user2.UserRegisterResp, error) {
	l := userlogic.NewRegisterLogic(ctx, s.svcCtx)
	return l.Register(in)
}

func (s *UserServer) Info(ctx context.Context, in *user2.UserInfoReq) (*user2.UserInfoResp, error) {
	l := userlogic.NewInfoLogic(ctx, s.svcCtx)
	return l.Info(in)
}
