// Code generated by goctl. DO NOT EDIT.
// goctl 1.9.2
// Source: app.proto

package server

import (
	"context"

	"go-zero-box-rpc/api/user"
	"go-zero-box-rpc/app/internal/logic/hello"
	"go-zero-box-rpc/app/internal/svc"
)

type HelloServer struct {
	svcCtx *svc.ServiceContext
	user.UnimplementedHelloServer
}

func NewHelloServer(svcCtx *svc.ServiceContext) *HelloServer {
	return &HelloServer{
		svcCtx: svcCtx,
	}
}

func (s *HelloServer) World(ctx context.Context, in *user.HelloWorldReq) (*user.HelloWorldResp, error) {
	l := hellologic.NewWorldLogic(ctx, s.svcCtx)
	return l.World(in)
}
