// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/prf16/go-zero-box-rpc/app/internal/command"
	demo2 "github.com/prf16/go-zero-box-rpc/app/internal/command/demo"
	"github.com/prf16/go-zero-box-rpc/app/internal/config"
	"github.com/prf16/go-zero-box-rpc/app/internal/model"
	"github.com/prf16/go-zero-box-rpc/app/internal/model/messagemodel"
	"github.com/prf16/go-zero-box-rpc/app/internal/model/usermodel"
	"github.com/prf16/go-zero-box-rpc/app/internal/queue"
	message2 "github.com/prf16/go-zero-box-rpc/app/internal/queue/message"
	"github.com/prf16/go-zero-box-rpc/app/internal/services"
	"github.com/prf16/go-zero-box-rpc/app/internal/services/demo"
	"github.com/prf16/go-zero-box-rpc/app/internal/services/message"
	"github.com/prf16/go-zero-box-rpc/app/internal/svc"
	"github.com/prf16/go-zero-box-rpc/pkg"
	"github.com/prf16/go-zero-box-rpc/pkg/asynqx"
	"github.com/prf16/go-zero-box-rpc/pkg/database"
	"github.com/prf16/go-zero-box-rpc/pkg/redis"
)

// Injectors from wire.go:

func initApp(c *config.Config) *App {
	databaseConfig := c.Database
	databaseDefault := database.NewDefault(databaseConfig)
	userModel := usermodel.NewUserModel(databaseDefault)
	messageModel := messagemodel.NewMessageModel(databaseDefault)
	modelModel := model.NewModel(userModel, messageModel)
	service := demo.NewService(userModel)
	messageService := message.NewService()
	servicesServices := services.NewServices(service, messageService)
	databaseDatabase := database.NewDatabase(databaseDefault)
	redisConfig := c.Redis
	redisDefault := redis.NewDefault(redisConfig)
	redisRedis := redis.NewRedis(redisDefault)
	asynqxConfig := c.Asynqx
	client := asynqx.NewClient(asynqxConfig)
	asynq := asynqx.NewAsynq(client)
	pkgPkg := pkg.NewPkg(databaseDatabase, redisRedis, asynq)
	serviceContext := svc.NewServiceContext(c, modelModel, servicesServices, pkgPkg)
	mailQueue := message2.NewMailQueue(messageService)
	smsQueue := message2.NewSmsQueue(messageService)
	wechatQueue := message2.NewWechatQueue(messageService)
	queueQueue := queue.NewQueue(mailQueue, smsQueue, wechatQueue)
	hello := demo2.NewHello()
	commandCommand := command.NewCommand(hello)
	app := NewApp(c, serviceContext, queueQueue, commandCommand, pkgPkg)
	return app
}

// wire.go:

type App struct {
	config  *config.Config
	svcCtx  *svc.ServiceContext
	queue   *queue.Queue
	command *command.Command
	pkg     *pkg.Pkg
}

func NewApp(config2 *config.Config, svcCtx *svc.ServiceContext, queue2 *queue.Queue, command2 *command.Command, pkg2 *pkg.Pkg) *App {
	return &App{config: config2, svcCtx: svcCtx, queue: queue2, command: command2, pkg: pkg2}
}
