// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/prf16/go-zero-box-rpc/app/internal/config"
	"github.com/prf16/go-zero-box-rpc/app/internal/svc"
	"github.com/prf16/go-zero-box-rpc/app/internal/svc/command"
	"github.com/prf16/go-zero-box-rpc/app/internal/svc/command/hello"
	"github.com/prf16/go-zero-box-rpc/app/internal/svc/model"
	"github.com/prf16/go-zero-box-rpc/app/internal/svc/model/messagemodel"
	"github.com/prf16/go-zero-box-rpc/app/internal/svc/model/usermodel"
	"github.com/prf16/go-zero-box-rpc/app/internal/svc/queue"
	message2 "github.com/prf16/go-zero-box-rpc/app/internal/svc/queue/message"
	"github.com/prf16/go-zero-box-rpc/app/internal/svc/services"
	"github.com/prf16/go-zero-box-rpc/app/internal/svc/services/demo"
	"github.com/prf16/go-zero-box-rpc/app/internal/svc/services/message"
	"github.com/prf16/go-zero-box-rpc/pkg"
	"github.com/prf16/go-zero-box-rpc/pkg/asynqx"
	"github.com/prf16/go-zero-box-rpc/pkg/database"
	"github.com/prf16/go-zero-box-rpc/pkg/redis"
)

// Injectors from wire.go:

func initApp(c *config.Config) *App {
	databaseConfig := c.Database
	databaseDefault := database.NewDefault(databaseConfig)
	databaseDatabase := database.NewDatabase(databaseDefault)
	redisConfig := c.Redis
	redisDefault := redis.NewDefault(redisConfig)
	redisRedis := redis.NewRedis(redisDefault)
	client := asynqx.NewClient(redisConfig)
	asynq := asynqx.NewAsynq(client)
	pkgPkg := pkg.NewPkg(databaseDatabase, redisRedis, asynq)
	world := hello.NewWorld()
	commandCommand := command.NewCommand(world)
	userModel := usermodel.NewUserModel(databaseDefault)
	messageModel := messagemodel.NewMessageModel(databaseDefault)
	modelModel := model.NewModel(userModel, messageModel)
	service := message.NewService()
	mailQueue := message2.NewMailQueue(service)
	smsQueue := message2.NewSmsQueue(service)
	wechatQueue := message2.NewWechatQueue(service)
	queueQueue := queue.NewQueue(mailQueue, smsQueue, wechatQueue)
	demoService := demo.NewService(userModel)
	servicesServices := services.NewServices(demoService, service)
	serviceContext := svc.NewServiceContext(c, pkgPkg, commandCommand, modelModel, queueQueue, servicesServices)
	app := NewApp(c, serviceContext, pkgPkg)
	return app
}

// wire.go:

type App struct {
	config *config.Config
	svcCtx *svc.ServiceContext
	pkg    *pkg.Pkg
}

func NewApp(config2 *config.Config, svcCtx *svc.ServiceContext, pkg2 *pkg.Pkg) *App {
	return &App{config: config2, svcCtx: svcCtx, pkg: pkg2}
}
