// Code generated by goctl. DO NOT EDIT.

package usermodel

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/Masterminds/squirrel"
	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
	"go-zero-box-rpc/app/internal/utils/tools"
	"reflect"
)

var (
	userFieldNames          = builder.RawFieldNames(&User{})
	userRows                = strings.Join(userFieldNames, ",")
	userRowsExpectAutoSet   = strings.Join(stringx.Remove(userFieldNames, "`id`", "`created_at`", "`updated_at`"), ",")
	userRowsWithPlaceHolder = strings.Join(stringx.Remove(userFieldNames, "`id`", "`created_at`", "`updated_at`"), "=?,") + "=?"
)

type (
	userModel interface {
		WithSession(session sqlx.Session) *defaultUserModel
		Insert(ctx context.Context, data *User) (sql.Result, error)
		InsertWithUpdate(ctx context.Context, data *User) error
		InsertWithUpdateField(ctx context.Context, data *User, fields []string) error
		BatchInsert(ctx context.Context, list []*User) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*User, error)
		Update(ctx context.Context, data *User) error
		UpdateField(ctx context.Context, data *User, fields []string) error

		Select(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*User, error)
		First(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*User, error)
		Count(ctx context.Context, rowBuilder squirrel.SelectBuilder) (int64, error)
		Avg(ctx context.Context, rowBuilder squirrel.SelectBuilder, field string) (float64, error)
		Sum(ctx context.Context, rowBuilder squirrel.SelectBuilder, field string) (float64, error)
		Max(ctx context.Context, rowBuilder squirrel.SelectBuilder, field string) (float64, error)
		Min(ctx context.Context, rowBuilder squirrel.SelectBuilder, field string) (float64, error)
		Aggregate(ctx context.Context, rowBuilder squirrel.SelectBuilder) (float64, error)
		DeleteFilter(ctx context.Context, where squirrel.Sqlizer) (sql.Result, error)
		UpdateFilter(ctx context.Context, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error)
		SelectGroup(ctx context.Context, rowBuilder squirrel.SelectBuilder, resp interface{}) error
		SelectGroupCount(ctx context.Context, rowBuilder squirrel.SelectBuilder) (int64, error)
		FirstCustom(ctx context.Context, rowBuilder squirrel.SelectBuilder, resp interface{}) error
		SelectCustom(ctx context.Context, rowBuilder squirrel.SelectBuilder, resp interface{}) error
		Customs(ctx context.Context, rowBuilder squirrel.SelectBuilder, resp interface{}) error
		Custom(ctx context.Context, rowBuilder squirrel.SelectBuilder, resp interface{}) error

		Delete(ctx context.Context, id uint64) error
		TableName() string
	}

	defaultUserModel struct {
		conn  sqlx.SqlConn
		table string
	}

	User struct {
		Id        uint64    `db:"id" json:"id"`
		Uuid      string    `db:"uuid" json:"uuid"`
		Account   string    `db:"account" json:"account"`       // 用户名
		Name      string    `db:"name" json:"name"`             // 姓名
		Mobile    string    `db:"mobile" json:"mobile"`         // 手机号
		Email     string    `db:"email" json:"email"`           // 邮箱
		Password  string    `db:"password" json:"password"`     // 密码
		Gender    int64     `db:"gender" json:"gender"`         // 性别
		Note      string    `db:"note" json:"note"`             // 备注
		Status    uint64    `db:"status" json:"status"`         // 状态 1启动 2禁用
		IsDelete  uint64    `db:"is_delete" json:"is_delete"`   // 是否删除 1是 2否
		CreatedAt time.Time `db:"created_at" json:"created_at"` // 创建时间
		UpdatedAt time.Time `db:"updated_at" json:"updated_at"` // 更新时间
	}
)

func newUserModel(conn sqlx.SqlConn) *defaultUserModel {
	return &defaultUserModel{
		conn:  conn,
		table: "`user`",
	}
}

func (m *defaultUserModel) WithSession(session sqlx.Session) *defaultUserModel {
	return &defaultUserModel{
		conn:  sqlx.NewSqlConnFromSession(session),
		table: "`user`",
	}
}
func (m *defaultUserModel) Delete(ctx context.Context, id uint64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}
func (m *defaultUserModel) FindOne(ctx context.Context, id uint64) (*User, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userRows, m.table)
	var resp User
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Insert(ctx context.Context, data *User) (sql.Result, error) {
	m.Init(data)
	data.CreatedAt = time.Now()
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Uuid, data.Account, data.Name, data.Mobile, data.Email, data.Password, data.Gender, data.Note, data.Status, data.IsDelete)
	return ret, err
}

func (m *defaultUserModel) InsertWithUpdate(ctx context.Context, data *User) error {
	if data.Id == 0 {
		m.Init(data)
		data.CreatedAt = time.Now()
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
		ret, err := m.conn.ExecCtx(ctx, query, data.Uuid, data.Account, data.Name, data.Mobile, data.Email, data.Password, data.Gender, data.Note, data.Status, data.IsDelete)
		id, err := ret.LastInsertId()
		if err != nil {
			return err
		}
		data.Id = uint64(id)
		return err
	} else {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRowsWithPlaceHolder)
		_, err := m.conn.ExecCtx(ctx, query, data.Uuid, data.Account, data.Name, data.Mobile, data.Email, data.Password, data.Gender, data.Note, data.Status, data.IsDelete, data.Id)
		return err
	}
}

func (m *defaultUserModel) InsertWithUpdateField(ctx context.Context, data *User, fields []string) error {
	if data.Id == 0 {
		m.Init(data)
		data.CreatedAt = time.Now()
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userRowsExpectAutoSet)
		ret, err := m.conn.ExecCtx(ctx, query, data.Uuid, data.Account, data.Name, data.Mobile, data.Email, data.Password, data.Gender, data.Note, data.Status, data.IsDelete)
		id, err := ret.LastInsertId()
		if err != nil {
			return err
		}
		data.Id = uint64(id)
		return err
	} else {
		err := m.UpdateField(ctx, data, fields)
		return err
	}
}

func (m *defaultUserModel) BatchInsert(ctx context.Context, list []*User) (sql.Result, error) {
	rowBuilder := squirrel.Insert(m.table).Columns(strings.Split(userRowsExpectAutoSet, ",")...)

	for _, data := range list {
		m.Init(data)
		data.CreatedAt = time.Now()
		rowBuilder = rowBuilder.Values(data.Uuid, data.Account, data.Name, data.Mobile, data.Email, data.Password, data.Gender, data.Note, data.Status, data.IsDelete)
	}

	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	resp, err := m.conn.ExecCtx(ctx, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Update(ctx context.Context, data *User) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Uuid, data.Account, data.Name, data.Mobile, data.Email, data.Password, data.Gender, data.Note, data.Status, data.IsDelete, data.Id)
	return err
}

func (m *defaultUserModel) UpdateField(ctx context.Context, data *User, fields []string) error {
	if data.Id == 0 || len(fields) == 0 {
		return nil
	}

	var fieldVals []interface{}
	for _, column := range fields {
		fieldVal := reflect.ValueOf(data).Elem().FieldByName(tools.UderscoreToUpperCamelCase(column)).Interface()
		fieldVals = append(fieldVals, fieldVal)
	}

	fieldVals = append(fieldVals, data.Id)

	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, strings.Join(fields, "=?,")+"=?")
	_, err := m.conn.ExecCtx(ctx, query, fieldVals...)
	if err != nil {
		return err
	}

	return nil
}

func (m *defaultUserModel) Select(ctx context.Context, rowBuilder squirrel.SelectBuilder) ([]*User, error) {
	query, values, err := rowBuilder.From(m.table).ToSql()
	if err != nil {
		return nil, err
	}

	var resp []*User
	err = m.conn.QueryRowsPartialCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserModel) First(ctx context.Context, rowBuilder squirrel.SelectBuilder) (*User, error) {
	query, values, err := rowBuilder.From(m.table).ToSql()
	if err != nil {
		return nil, err
	}

	var resp User
	err = m.conn.QueryRowPartialCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return &resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserModel) Count(ctx context.Context, rowBuilder squirrel.SelectBuilder) (int64, error) {
	query, values, err := rowBuilder.RemoveColumns().From(m.table).RemoveOffset().RemoveLimit().Columns("count(*) as c").ToSql()
	if err != nil {
		return 0, err
	}

	var resp int64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserModel) Avg(ctx context.Context, rowBuilder squirrel.SelectBuilder, field string) (float64, error) {
	query, values, err := rowBuilder.RemoveColumns().From(m.table).Columns("IFNULL(AVG(" + field + "),0)").ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserModel) Sum(ctx context.Context, rowBuilder squirrel.SelectBuilder, field string) (float64, error) {
	query, values, err := rowBuilder.RemoveColumns().From(m.table).Columns("IFNULL(SUM(" + field + "),0)").ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserModel) Max(ctx context.Context, rowBuilder squirrel.SelectBuilder, field string) (float64, error) {
	query, values, err := rowBuilder.RemoveColumns().From(m.table).Columns("IFNULL(MAX(" + field + "),0)").ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserModel) Min(ctx context.Context, rowBuilder squirrel.SelectBuilder, field string) (float64, error) {
	query, values, err := rowBuilder.RemoveColumns().From(m.table).Columns("IFNULL(Min(" + field + "),0)").ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserModel) Aggregate(ctx context.Context, rowBuilder squirrel.SelectBuilder) (float64, error) {
	query, values, err := rowBuilder.From(m.table).ToSql()
	if err != nil {
		return 0, err
	}

	var resp float64
	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return resp, nil
	default:
		return 0, err
	}
}

func (m *defaultUserModel) DeleteFilter(ctx context.Context, where squirrel.Sqlizer) (sql.Result, error) {
	query, values, err := squirrel.Delete(m.table).Where(where).ToSql()
	if err != nil {
		return nil, err
	}

	resp, err := m.conn.ExecCtx(ctx, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserModel) UpdateFilter(ctx context.Context, updateData map[string]interface{}, where squirrel.Sqlizer) (sql.Result, error) {
	rowBuilder := squirrel.Update(m.table)
	for column, value := range updateData {
		rowBuilder = rowBuilder.Set(fmt.Sprintf("`%s`", column), value)
	}
	rowBuilder = rowBuilder.Where(where)
	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return nil, err
	}

	resp, err := m.conn.ExecCtx(ctx, query, values...)
	switch err {
	case nil:
		return resp, nil
	default:
		return nil, err
	}
}

func (m *defaultUserModel) SelectGroup(ctx context.Context, rowBuilder squirrel.SelectBuilder, resp interface{}) error {
	resp = tools.GetPointer(resp)

	query, values, err := rowBuilder.From(m.table).ToSql()
	if err != nil {
		return err
	}

	err = m.conn.QueryRowsPartialCtx(ctx, resp, query, values...)
	switch err {
	case nil:
		return nil
	case sqlc.ErrNotFound:
		return nil
	default:
		return err
	}
}

func (m *defaultUserModel) SelectGroupCount(ctx context.Context, rowBuilder squirrel.SelectBuilder) (int64, error) {
	var resp int64
	query, values, err := rowBuilder.From(m.table).RemoveOffset().RemoveLimit().ToSql()
	if err != nil {
		return resp, err
	}

	query = fmt.Sprintf("SELECT COUNT(*) as c FROM ( %s ) t", query)

	err = m.conn.QueryRowCtx(ctx, &resp, query, values...)
	switch err {
	case nil:
		return resp, nil
	case sqlc.ErrNotFound:
		return resp, nil
	default:
		return resp, err
	}
}

func (m *defaultUserModel) FirstCustom(ctx context.Context, rowBuilder squirrel.SelectBuilder, resp interface{}) error {
	resp = tools.GetPointer(resp)

	query, values, err := rowBuilder.From(m.table).ToSql()
	if err != nil {
		return err
	}

	err = m.conn.QueryRowPartialCtx(ctx, resp, query, values...)
	switch err {
	case nil:
		return nil
	case sqlc.ErrNotFound:
		return nil
	default:
		return err
	}
}

func (m *defaultUserModel) SelectCustom(ctx context.Context, rowBuilder squirrel.SelectBuilder, resp interface{}) error {
	resp = tools.GetPointer(resp)

	query, values, err := rowBuilder.From(m.table).ToSql()
	if err != nil {
		return err
	}

	err = m.conn.QueryRowsPartialCtx(ctx, resp, query, values...)
	switch err {
	case nil:
		return nil
	case sqlc.ErrNotFound:
		return nil
	default:
		return err
	}
}

func (m *defaultUserModel) Customs(ctx context.Context, rowBuilder squirrel.SelectBuilder, resp interface{}) error {
	resp = tools.GetPointer(resp)

	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return err
	}

	err = m.conn.QueryRowsPartialCtx(ctx, resp, query, values...)
	switch err {
	case nil:
		return nil
	case sqlc.ErrNotFound:
		return nil
	default:
		return err
	}
}

func (m *defaultUserModel) Custom(ctx context.Context, rowBuilder squirrel.SelectBuilder, resp interface{}) error {
	resp = tools.GetPointer(resp)

	query, values, err := rowBuilder.ToSql()
	if err != nil {
		return err
	}

	err = m.conn.QueryRowPartialCtx(ctx, resp, query, values...)
	switch err {
	case nil:
		return nil
	case sqlc.ErrNotFound:
		return nil
	default:
		return err
	}
}

func (m *defaultUserModel) TableName() string {
	return m.table
}
